# Generated by Django 3.2.9 on 2021-12-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapplicationswhiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='title_tag',
            field=models.CharField(default='my career whiz', max_length=255),
        ),
    ]
