# Generated by Django 3.2.9 on 2021-12-02 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapplicationswhiz', '0002_application_title_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='notes',
        ),
    ]
