# Generated by Django 3.2.9 on 2021-12-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapplicationswhiz', '0003_remove_application_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='application',
            name='title_tag',
        ),
    ]
