# Generated by Django 3.2.9 on 2021-12-02 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapplicationswhiz', '0005_rename_user_application_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
