# Generated by Django 3.2.9 on 2021-12-02 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapplicationswhiz', '0007_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='owner',
            new_name='user',
        ),
    ]
