# Generated by Django 3.2.9 on 2021-12-03 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theapplicationswhiz', '0010_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Feeding Date')),
                ('interview', models.CharField(choices=[('V', 'Video-Conferencing'), ('H', 'Hybrid'), ('O', 'In-Office')], default='V', max_length=1)),
                ('Application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theapplicationswhiz.application')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
