# Generated by Django 3.2.9 on 2021-12-03 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapplicationswhiz', '0011_interviewing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interviewing',
        ),
    ]
