# Generated by Django 3.2.9 on 2021-12-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapplicationswhiz', '0013_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='category',
            field=models.CharField(default='uncategorized', max_length=255),
        ),
    ]
