# Generated by Django 3.2.9 on 2021-12-05 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theapplicationswhiz', '0018_contact_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='theapplicationswhiz.application'),
        ),
    ]
