# Generated by Django 3.2.9 on 2021-12-05 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapplicationswhiz', '0020_contact_date_added'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
