# Generated by Django 3.2.9 on 2021-12-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapplicationswhiz', '0022_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='linkedin_profile',
            field=models.TextField(default='null'),
        ),
    ]
