# Generated by Django 3.2.9 on 2021-12-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapplicationswhiz', '0024_auto_20211205_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(default='notapplied', max_length=255),
        ),
    ]
